version: "3"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    restart: unless-stopped
    ports:
      - "58081:8081"
      - "8765:8765"
    volumes:
      - etc_motioneye:/etc/motioneye
      - var_lib_motioneye:/var/lib/motioneye
      - ./pushbullet.sh:/var/lib/scripts/pushbullet.sh
    networks:
      - motion_net
volumes:
  etc_motioneye:
  var_lib_motioneye:
networks:
  motion_net: